# Generated by Django 4.2 on 2024-04-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='edited_at',
            new_name='date_edited',
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postfield',
            name='content_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postfield',
            name='content_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postfield',
            name='content_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postfield',
            name='content_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postfield',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='postfield',
            name='content_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posttemplate',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttemplate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatefield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime'), ('file', 'File'), ('image', 'Image')], default='text', max_length=100, unique=True),
        ),
    ]
