# Generated by Django 4.2 on 2024-04-21 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_rename_created_at_post_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='followers',
            field=models.ManyToManyField(related_name='followed_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
