# Generated by Django 4.2 on 2024-04-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefield',
            name='field',
        ),
        migrations.AddField(
            model_name='templatefield',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime'), ('file', 'File'), ('image', 'Image')], default='text', max_length=100),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
