# Generated by Django 4.2 on 2024-05-12 13:29

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_postfield_content_textarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=community.models.community_photo_upload),
        ),
    ]
