# Generated by Django 4.2 on 2024-05-12 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0007_post_view_count_postviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postviews', to='community.post'),
        ),
        migrations.AlterField(
            model_name='postviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewedposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
