# Generated by Django 4.2 on 2024-05-14 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0008_alter_postviews_post_alter_postviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfield',
            name='content_geolocation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Datetime'), ('file', 'File'), ('image', 'Image'), ('geolocation', 'Geolocation')], default='text', max_length=100),
        ),
    ]
